variables: secrets.yml

web_server: yes
#web_server:
#  bind: 0.0.0.0
#  port: 5050
#api: yes
#webui: yes

schedules:
  - tasks: ['populate-*', 'clean-*', 'update-*']
    schedule:
      minute: 0,30
  - tasks: ['purge-*', 'fill-*'] # , '*-rss', '*-magnets'
    schedule:
      minute: 0,30
  - tasks: ['*-discover', '*-manual']
    schedule:
      minute: 0,15,30,45

templates:

##### Series config
  series:
    thetvdb_lookup: yes
    configure_series:
      from:
        entry_list: trakt-series
      settings:
        timeframe: 12 hours
        target:  1080p+ h265
        propers: 24 hours
        identified_by: ep
    content_size:
      min: 150
      max: 2400
    content_filter:
      require:
        - '*.mkv'


##### Movies config
  movie-list-match:
    list_match:
      from:
        - movie_list: trakt-movies

  movies-3d:
    tmdb_lookup: yes
    movie_list: trakt-movies
    quality:  1080p+ webdl+ 
    content_size:
      min: 1000
      max: 25000
    regexp:
      accept:
        - (3D|3d)
      reject:
        - (2D|2d)

      
  movies-2160p-webdl:
    tmdb_lookup: yes
    movie_list: trakt-movies
    regexp:
      accept:
        - (2160p|4K|4k)
      reject:
        - (480|720|1080)
      from: title
    quality:  webdl+
    content_size:
      min: 2000
      max: 60000

  movies-2160p-h264:
    tmdb_lookup: yes
    movie_list: trakt-movies
    regexp:
      accept:
        - (2160p|4K|4k)
      reject:
        - (480|720|1080)
      from: title
    quality:  h264+
    content_size:
      min: 2000
      max: 60000
      
  movies-1080p:
    template:
      - movie-list-match
    tmdb_lookup: yes
    movie_list: trakt-movies
    quality: 1080i+ hdtv+ h265
    content_size:
      min: 500
      max: 18000

  movies-720p:
    template:
      - movie-list-match
    tmdb_lookup: yes
    movie_list: trakt-movies
    quality: 720i+ hdtv+ 
    content_size:
      min: 250
      max: 5000
      
  trakt-movies-remove:
    list_remove:
      - movie_list: trakt-movies
      - trakt_list:
          account: '{? trakt.account ?}'
          list: '{? trakt.moviesqueue ?}'
          type: movies
  trakt-movies-add:        
    list_add:
      - trakt_list:
          account: '{? trakt.account ?}'
          list: '{? trakt.movieswatchlist ?}'
          type: movies      

##### Transmission config
  transmission-anchors:
    _transmission-settings: &transmission-settings
      host: '{? transmission.host ?}'
      port: 9091
      username: '{? transmission.user ?}'
      password: '{? transmission.pass ?}'

##### Common rejections
  reject:
    regexp:
      reject:
        - (s|d)ub(s|bed|lado|titulado)?\b
        - \bdual\b
        - \b(fr)(ench)?\b
        - \b(ita)(lian)?\b
        - \b(spa)(nish)?\b
        - \b(ger)(man)?\b
        - \bcastellano\b
        - \brus(sian)?\b
    content_filter:
      reject:
        - '*.rar'
        - '*.zip'


##### ADVANCED SETTINGS #####

##### Global config
  global:
    no_entries_ok: yes
    pathscrub: windows
    free_space:
      path: '/{? folder.root ?}'
      space: 5000
    # Requires log_filter plugin
    log_filter:
      task:
        - marked seen
        - because quality already downloaded
        - because episode has already been downloaded
        - Task does not have any
      move:
        - left because it exceeds safety value
        - does not exists (anymore)
      urlrewriter:
        - URL rewritten to
      enzyme.mkv:
        - Reading
        - Processing
      enzyme.parsers.ebml.core:
        - ignored
        - Maximum level
      subliminal.video:
        - Scanning video
      parser_internal:
        - appears to be an episode pack
      content_size:
        - rejecting
      search_rss:
        - Error
      assume_quality:
        - ""
      utils.requests:
        - Waiting

##### Common torrents config
  torrents:
    torrent_alive:
      min_seeds: 3
      reject_for: 15 minutes
    magnets: no
    # Might need to disable if you are getting errors connecting to https sources
    # Can remove if you upgrade to python 2.7.9+ or install requests[security]
    verify_ssl_certificates: no
    domain_delay:
      iptorrents.eu: 1 seconds

##### Transmission series config
  transmission-series:
    transmission:
      <<: *transmission-settings
      addpaused: no 
#      main_file_only: yes
      include_subs: yes
      rename_like_files: yes
      content_filename: "{% if tvdb_episode|default(False) and tvdb_ep_name|default(False) %}{{tvdb_series_name|pathscrub|re_replace(' \\([0-9]*\\)','')}} {{tvdb_season}}x{{tvdb_episode|pad(2)}} - {{tvdb_ep_name|pathscrub}}{% else %}{{title}}{% endif %}"  
#      content_filename: "{{tvdb_series_name|default(series_name)|pathscrub}} - {{tvdb_ep_id|default(series_id)}}{% if tvdb_ep_name|default(False) %} - {{tvdb_ep_name|pathscrub}}{% endif %}{% if quality|default(False) %} - [{{quality}}]{% endif %}"
      path: "/{? folder.root ?}{? folder.series ?}{{tvdb_series_name|default(series_name)|pathscrub}}/"

##### Transmission movies config
  transmission-movies:
    transmission:
      <<: *transmission-settings
      addpaused: no 
      main_file_only: no
#      include_subs: yes
      rename_like_files: yes
      content_filename: "{{tmdb_name|pathscrub}} ({{tmdb_year}}){% if quality|default(False) %} - [{{quality}}]{% endif %}"
      path: "/{? folder.root ?}{? folder.movies ?}{{movie_name|pathscrub}}"

##### Pushbullet config
  pushbullet:
    notify:
      entries:
        via:
          - pushbullet:
              api_key: '{? pushbullet.api ?}'
              channel: '{? pushbullet.channel ?}'

##### Disable builtins for some tasks
  disable-seen-retry:
    disable:
      - seen
      - seen_info_hash
      - retry_failed

##### Series metainfo mainly for move and update tasks
  series-metainfo:
    trakt_lookup: yes
    imdb_lookup: yes
    metainfo_series: yes
    thetvdb_lookup: yes

##### Guessit parsing for some series tasks and anime, not applied to all tasks because it causes issues with "name (year)" based series, like scandal
  series-guessit:
    parsing:
      series: guessit

##### Movies metainfo mainly for move and update tasks
  movies-metainfo:
    tmdb_lookup: yes
    parsing:
      movie: guessit
  

  download-movies-discover-base:   
    template:
        - reject
        - torrents
        - transmission-movies
        - pushbullet
        - trakt-movies-remove
        - trakt-movies-add
    exists_movie:
      - '/{? folder.root ?}{? folder.movies ?}'
    discover:
      release_estimations: loose
      interval: 15 minutes
      what:
        - movie_list: trakt-movies
      from:
        - iptorrents: 
            rss_key: '{? iptorrents.rss_key ?}' 
            uid: 1486500 
            password: '{? iptorrents.password ?}'
            category:
              - 87 #Movies 3D
              - 48 #Movie HD
              - 20 #Movie Web DL
              - Movie-HD-Bluray
              - Movie-MP4
              - Movie-BD-Rip
              - Movie-3D
#    list_add:
#      - trakt_list:
#          account: '{? trakt.account ?}'
#          list: '{? trakt.movieswatchlist ?}'
#          type: movies
          


tasks:

##### Populates the series database with the files on the library, to avoid duplicate downloads
  populate-series-db:
    priority: 1
    template:
      - series-metainfo
    seen: local
    filesystem:
      path: '/{? folder.root ?}{? folder.series ?}'
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    configure_series:
      from:
        filesystem:
          path: '/{? folder.root ?}{? folder.series ?}'
          retrieve: dirs
      settings:
        tracking: no


##### Purge the series list to allow full sync with trakt series list
  purge-series-list:
    priority: 2
    template:
      - disable-seen-retry
    entry_list: trakt-series
    accept_all: yes
    list_remove:
      - entry_list: trakt-series


##### Fetch, format and output trakt series list to a custom entry list
  fill-series-list:
    priority: 3
    template:
      - disable-seen-retry
      - series-metainfo
    trakt_list:
      account: '{? trakt.account ?}'
      list: '{? trakt.series ?}'
      type: shows
    accept_all: yes
    set:
      title: "{{ tvdb_series_name|escape|replace('&#39;', '') }}"
    list_add:
      - entry_list: trakt-series


##### Download episodes from manually downloaded torrents
  download-series-manual:
    priority: 11
    template:
      - disable-seen-retry
      - series-metainfo
      - series-guessit
      - transmission-series
      - pushbullet
    filesystem:
      path: '/{? folder.root ?}{? folder.series ?}'
      mask: '*.torrent'
    accept_all: yes
    exec:
      on_output:
        for_accepted: rm -f "{{location}}"



##### Discover and download older episodes and pilots from recently added series
  download-series-discover:
    priority: 14
    template:
      - series
      - reject
      - torrents
      - transmission-series
      - pushbullet
    discover:
      release_estimations: ignore
      interval: 5 minutes
      what:
        - next_series_episodes: yes
      from:
        - iptorrents: 
            rss_key: '{? iptorrents.rss_key ?}'
            uid: 1486500 
            password: '{? iptorrents.password ?}'
            category: 
              - TV-480p 
              - TV-SD-x264
              - TV-Web-DL
              - TV-x264  
              - 99 #TV-x265
              - TV-MP4


##### Remove manually downloaded movies from the movie queue and trakt list
  clean-movie-queue:
    priority: 22
    template:
      - disable-seen-retry
      - movies-metainfo
      - trakt-movies-remove
    filesystem:
      path: '/{? folder.root ?}{? folder.movies ?}'
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes


##### Fill the movie queue with movies from trakt list
  fill-movie-queue:
    priority: 23
    trakt_list:
      account: '{? trakt.account ?}'
      list: '{? trakt.moviesqueue ?}'
      type: movies
      strip_dates: yes
    accept_all: yes
    list_add:
      - movie_list: trakt-movies


##### Download movies manually downloaded torrents
  download-movies-manual:
    priority: 24
    template:
      - disable-seen-retry
      - movies-metainfo
      - transmission-movies
      - pushbullet
      - trakt-movies-remove
    filesystem:
      path: '/{? folder.root ?}{? folder.movies ?}'
      mask: '*.torrent'
    accept_all: yes
    exec:
      on_output:
        for_accepted: rm -f "{{location}}"
          

##### Discover and download 3D movies
  download-movies-3D-discover:
    priority: 24
    template:
      - download-movies-discover-base
      - movies-3d
    

##### Discover and download 2160p movies
  download-movies-2160p-webdl-discover:
    priority: 25
    template:
      - download-movies-discover-base
      - movies-2160p-webdl

  download-movies-2160p-h264-discover:
    priority: 25
    template:
      - download-movies-discover-base
      - movies-2160p-h264

          

##### Discover and download 1080p movies
  download-movies-1080p-discover:
    priority: 26
    template:
      - download-movies-discover-base
      - movies-1080p



##### Discover and download 720p movies, if the movie is not recent
  download-movies-720p-discover:
    priority: 27
    template:
      - download-movies-discover-base
      - movies-720p

##### Clean finished torrents from transmission
  clean-transmission:
    priority: 37
    disable: details
    clean_transmission:
      <<: *transmission-settings
      finished_for: 18 day


##### Update trakt series list from local series folders, excluding the ones that already ended
  update-series-list:
    priority: 41
    template:
      - disable-seen-retry
      - series-metainfo
    filesystem:
      path: '/{? folder.root ?}{? folder.series ?}'
      retrieve: dirs
    manipulate:
      - title:
          replace:
            regexp: '$'
            format: ' S01E01'
    accept_all: yes
    if:
      - tvdb_status == 'Ended': reject
    list_add:
      - trakt_list:
          account: '{? trakt.account ?}'
          list: '{? trakt.series ?}'
          type: shows


##### Clean the series that already ended from trakt series list
  clean-series-list:
    priority: 43
    delay: 8 day
    template:
      - disable-seen-retry
      - series-metainfo
      - pushbullet
    trakt_list:
      account: '{? trakt.account ?}'
      list: '{? trakt.series ?}'
      type: shows
    if:
      - tvdb_status == 'Ended': accept
    list_remove:
      - trakt_list:
          account: '{? trakt.account ?}'
          list: '{? trakt.series ?}'
          type: shows

