secrets: secrets.yml

web_server:
  bind: 0.0.0.0
  port: 5050
api: yes
webui: yes

schedules:
  - tasks: ['populate-*', 'clean-*', 'update-*']
    schedule:
      hour: 0
  - tasks: ['purge-*', 'fill-*'] # , '*-rss', '*-magnets'
    schedule:
      minute: 0,30
  - tasks: ['*-discover', '*-manual']
    schedule:
      hour: '*/2'
  - tasks: ['move-*', download-subtitles]
    schedule:
      minute: 15,45

templates:

##### Series config
#
  series:
    thetvdb_lookup: yes
#    include: series.yml
    configure_series:
      from:
        entry_list: trakt-series
      settings:
        identified_by: ep
        timeframe: 12 hours
        target: hdtv+ 1080p  h265
        quality: webrip+ 480p 
        propers: 12 hours
        specials: no
    content_size:
      min: 200
    content_filter:
      require:
        - '*.mkv'

##### Anime config
#
  anime:
#    include: anime.yml
    configure_series:
      from:
        entry_list: myanimelist-series
      settings:
        identified_by: sequence
        quality: 720p 
        special_ids:
          - OVA

##### Movies config
#
  movie-list-match:
    list_match:
      from:
        - movie_list: trakt-movies

  movies-3d:
    tmdb_lookup: yes
    movie_list: trakt-movies
    quality:  1080p+ webdl+ 
    content_size:
      min: 1000
      max: 15000
    regexp:
      accept:
        - (3D|3d)
      reject:
        - (2D|2d)

      
  movies-2160p-webdl:
    tmdb_lookup: yes
    movie_list: trakt-movies
    regexp:
      accept:
        - (2160p|4K|4k)
      reject:
        - (480|720|1080)
      from: title
    quality:  webdl+
    content_size:
      min: 2000
      max: 60000

  movies-2160p-h264:
    tmdb_lookup: yes
    movie_list: trakt-movies
    regexp:
      accept:
        - (2160p|4K|4k)
      reject:
        - (480|720|1080)
      from: title
    quality:  h264+
    content_size:
      min: 2000
      max: 60000
      
  movies-1080p:
    template:
      - movie-list-match
    tmdb_lookup: yes
    movie_list: trakt-movies
    quality: 1080i+ hdtv+ h265
    content_size:
      min: 500
      max: 12000

  movies-720p:
    template:
      - movie-list-match
    tmdb_lookup: yes
    movie_list: trakt-movies
    quality: 720i+ hdtv+ 
    content_size:
      min: 250
      max: 5000
      
  trakt-movies-remove:
    list_remove:
      - movie_list: trakt-movies
      - trakt_list:
          account: '{{secrets.trakt.account}}'
          list: '{{secrets.trakt.moviesqueue}}'
          type: movies
  trakt-movies-add:        
    list_add:
      - trakt_list:
          account: '{{secrets.trakt.account}}'
          list: '{{secrets.trakt.movieswatchlist}}'
          type: movies      

##### Transmission config
#
  transmission-anchors:
    _transmission-settings: &transmission-settings
      host: '{{secrets.transmission.host}}'
      port: 9091
      username: '{{secrets.transmission.user}}'
      password: '{{secrets.transmission.pass}}'

##### Common rejections
#
  reject:
    regexp:
      reject:
        - (s|d)ub(s|bed|lado|titulado)?\b
        - \bdual\b
        - \b(fr)(ench)?\b
        - \b(ita)(lian)?\b
        - \b(spa)(nish)?\b
        - \b(ger)(man)?\b
        - \bcastellano\b
        - \brus(sian)?\b
    content_filter:
      reject:
        - '*.rar'
        - '*.zip'


##### ADVANCED SETTINGS #####

##### Global config
#
  global:
    no_entries_ok: yes
    pathscrub: windows
    free_space:
      path: '/{{secrets.folder.root}}'
      space: 5000
    # Requires log_filter plugin
    log_filter:
      task:
        - marked seen
        - because quality already downloaded
        - because episode has already been downloaded
        - Task does not have any
      move:
        - left because it exceeds safety value
        - does not exists (anymore)
      urlrewriter:
        - URL rewritten to
      enzyme.mkv:
        - Reading
        - Processing
      enzyme.parsers.ebml.core:
        - ignored
        - Maximum level
      subliminal.video:
        - Scanning video
      parser_internal:
        - appears to be an episode pack
      content_size:
        - rejecting
      search_rss:
        - Error
      assume_quality:
        - ""
      utils.requests:
        - Waiting

##### Common torrents config
#
  torrents:
    torrent_alive:
      min_seeds: 3
      reject_for: 15 minutes
    magnets: no
    # Might need to disable if you are getting errors connecting to https sources
    # Can remove if you upgrade to python 2.7.9+ or install requests[security]
    #verify_ssl_certificates: no
    domain_delay:
      thepiratebay.se: 1 seconds
      extratorrent.cc: 1 seconds
      nyaa.se: 1 seconds

##### Transmission series config
#
  transmission-series:
    transmission:
      <<: *transmission-settings
      addpaused: yes
      main_file_only: yes
      include_subs: yes
      rename_like_files: yes
      content_filename: "{{tvdb_series_name|default(series_name)|pathscrub}} - {{tvdb_ep_id|default(series_id)}}{% if tvdb_ep_name|default(False) %} - {{tvdb_ep_name|pathscrub}}{% endif %}{% if quality|default(False) %} - [{{quality}}]{% endif %}"
      path: "/{{secrets.folder.root}}{{secrets.folder.downseries}}{{tvdb_series_name|default(series_name)|pathscrub}}/"

##### Transmission anime config
#
  transmission-anime:
    transmission:
      <<: *transmission-settings
      addpaused: yes
      main_file_only: yes
      content_filename: "{{series_name}} - ep{{series_id}} - [{{quality}}]"
      path: "/{{secrets.folder.root}}{{secrets.folder.downanime}}{{series_name|pathscrub}}/"

##### Transmission movies config
#
  transmission-movies:
    transmission:
      <<: *transmission-settings
      addpaused: yes
      main_file_only: yes
      include_subs: yes
      rename_like_files: yes
      content_filename: "{{tmdb_name|pathscrub}} ({{tmdb_year}}){% if quality|default(False) %} - [{{quality}}]{% endif %}"
      path: "/{{secrets.folder.root}}{{secrets.folder.downmovies}}{{movie_name|pathscrub}}"

##### Pushbullet config
#
  pushbullet:
    pushbullet:
      apikey: '{{secrets.pushbullet.api}}'
      title: "[flexget] {{task}}"
      body: "{{title}}"

##### Disable builtins for some tasks
#
  disable-seen-retry:
    disable:
      - seen
      - seen_info_hash
      - retry_failed

##### Series metainfo mainly for move and update tasks
#
  series-metainfo:
    metainfo_series: yes
    thetvdb_lookup: yes

##### Guessit parsing for some series tasks and anime, not applied to all tasks because it causes issues with "name (year)" based series, like scandal
#
  series-guessit:
    parsing:
      series: guessit

##### Movies metainfo mainly for move and update tasks
#
  movies-metainfo:
    tmdb_lookup: yes
    parsing:
      movie: guessit
  

  download-movies-discover-base:   
    template:
        - reject
        - torrents
        - transmission-movies
        - pushbullet
        - trakt-movies-remove
        - trakt-movies-add
    exists_movie:
      - '/{{secrets.folder.root}}{{secrets.folder.downmovies}}'
      - '/{{secrets.folder.root}}{{secrets.folder.movies}}'
    discover:
      release_estimations: loose
      interval: 15 minutes
      what:
        - movie_list: trakt-movies
      from:
        - iptorrents: 
            rss_key: '{{ secrets.iptorrents.rss_key }}' 
            uid: 1486500 
            password: '{{ secrets.iptorrents.password }}'
            category:
              - 87 #Movies 3D
              - 48 #Movie HD
              - 20 #Movie Web DL
              - Movie-HD-Bluray
              - Movie-MP4
              - Movie-BD-Rip
              - Movie-3D
    
    list_add:
      - trakt_list:
          account: '{{secrets.trakt.account}}'
          list: '{{secrets.trakt.movieswatchlist}}'
          type: movies
          


tasks:

##### Populates the series database with the files on the library, to avoid duplicate downloads
#
  populate-series-db:
    priority: 1
    template:
      - series-metainfo
    seen: local
    filesystem:
      path: '/{{secrets.folder.root}}{{secrets.folder.series}}'
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    configure_series:
      from:
        filesystem:
          path: '/{{secrets.folder.root}}{{secrets.folder.series}}'
          retrieve: dirs
      settings:
        tracking: no


##### Purge the series list to allow full sync with trakt series list
#
  purge-series-list:
    priority: 2
    template:
      - disable-seen-retry
    entry_list: trakt-series
    accept_all: yes
    list_remove:
      - entry_list: trakt-series


##### Fetch, format and output trakt series list to a custom entry list
#
  fill-series-list:
    priority: 3
    template:
      - disable-seen-retry
      - series-metainfo
    trakt_list:
      account: '{{secrets.trakt.account}}'
      list: '{{secrets.trakt.series}}'
      type: shows
    accept_all: yes
    set:
      title: "{{tvdb_series_name|escape|replace('&#39;', '')}}"
    list_add:
      - entry_list: trakt-series


##### Purge the series list to allow full sync with myanimelist series list
#
  purge-anime-series-list:
    priority: 6
    template:
      - disable-seen-retry
    entry_list: myanimelist-series
    accept_all: yes
    list_remove:
      - entry_list: myanimelist-series


##### Fetch, format and output myanimelist series list to a custom entry list
#
#  fill-anime-series-list:
#    priority: 8
#    template:
#      - disable-seen-retry
#      - series-metainfo
#    myanimelist:
#      user_id: '{{secrets.myanimelist.id}}'
#      list: both
#    accept_all: yes
#    set:
#      title: "{{myanimelist_name|re_replace('[-/:;.★](?=[a-zA-Z])', ' ')|re_replace('[:;](?![a-zA-Z])|[`´()]|TV|', '')|re_replace('Season ', 'S')|re_replace('  +', ' ')}}"
#    list_add:
#      - entry_list: myanimelist-series


##### Download episodes from manually downloaded torrents
#
  download-series-manual:
    priority: 11
    template:
      - disable-seen-retry
      - series-metainfo
      - series-guessit
      - transmission-series
      - pushbullet
    filesystem:
      path: '/{{secrets.folder.root}}{{secrets.folder.downseries}}'
      mask: '*.torrent'
    accept_all: yes
    exec:
      on_output:
        for_accepted: rm -f "{{location}}"


##### Download episodes from RSS feeds
#
#  download-series-rss:
#    priority: 12
#    template:
#      - series
#      - reject
#      - torrents
#      - transmission-series
#      - pushbullet
#    inputs:
#      - rss: https://eztv.unblocked.live/ezrss.xml
#      - rss: https://extratorrent.cc/rss.xml?cid=8&type=last
#      - rss: https://www.torrentfunk.com/tv/rss.xml


##### Download episodes from RSS magnets feeds, as a fallback from the previous task
#
#  download-series-magnets:
#    priority: 13
#    template:
#      - series
#      - reject
#      - torrents
#      - transmission-series
#      - pushbullet
#    magnets: yes
#    convert_magnet: yes
#    inputs:
#      - rss:
#          url: http://showrss.info/feeds/all.rss
#          all_entries: yes


##### Discover and download older episodes and pilots from recently added series
#
  download-series-discover:
    priority: 14
    template:
      - series
      - reject
      - torrents
      - transmission-series
      - pushbullet
    discover:
      release_estimations: ignore
      interval: 15 minutes
      what:
        - next_series_episodes:
            from_start: yes
      from:
        - iptorrents: 
            rss_key: '{{ secrets.iptorrents.rss_key }}'
            uid: 1486500 
            password: '{{ secrets.iptorrents.password }}'
            category: 
              - TV-480p 
              - TV-SD-x264
              - TV-Web-DL
              - TV-x264  
              - 99 #TV-x265
              - TV-MP4

##### Download anime from manually downloaded torrents
#
  download-anime-manual:
    priority: 15
    template:
      - disable-seen-retry
      - series-guessit
      - transmission-anime
      - pushbullet
    filesystem:
      path: '/{{secrets.folder.root}}{{secrets.folder.downanime}}'
      mask: '*.torrent'
    accept_all: yes
    exec:
      on_output:
        for_accepted: rm -f "{{location}}"


##### Download anime from RSS feed
#
#  download-anime-rss:
#    priority: 16
#    template:
#      - anime
#      - torrents
#      - transmission-anime
#      - pushbullet
#    inputs:
#      - rss:
#          url: http://www.nyaa.se/?page=rss&cats=1_37
#          all_entries: yes


##### Discover and download anime
#
  download-anime-discover:
    priority: 17
    template:
      - anime
      - torrents
      - transmission-anime
      - pushbullet
    discover:
      release_estimations: ignore
      interval: 15 minutes
      what:
        - next_series_episodes:
            from_start: yes
            backfill: yes
      from:
        - iptorrents: 
            rss_key: '{{ secrets.iptorrents.rss_key }}'
            uid: 1486500 
            password: '{{ secrets.iptorrents.password }}'
            category: 
              - 60


##### Remove manually downloaded movies from the movie queue and trakt list
#
  clean-movie-queue:
    priority: 22
    template:
      - disable-seen-retry
      - movies-metainfo
      - trakt-movies-remove
    filesystem:
      path: '/{{secrets.folder.root}}{{secrets.folder.movies}}'
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes


##### Fill the movie queue with movies from trakt list
#
  fill-movie-queue:
    priority: 23
    trakt_list:
      account: '{{secrets.trakt.account}}'
      list: '{{secrets.trakt.moviesqueue}}'
      type: movies
      strip_dates: yes
    accept_all: yes
    list_add:
      - movie_list: trakt-movies


##### Download movies manually downloaded torrents
#
  download-movies-manual:
    priority: 24
    template:
      - disable-seen-retry
      - movies-metainfo
      - transmission-movies
      - pushbullet
      - trakt-movies-remove
    filesystem:
      path: '/{{secrets.folder.root}}{{secrets.folder.downmovies}}'
      mask: '*.torrent'
    accept_all: yes
    exec:
      on_output:
        for_accepted: rm -f "{{location}}"
          

##### Discover and download 3D movies
#
  download-movies-3D-discover:
    priority: 24
    template:
      - download-movies-discover-base
      - movies-3d
    

##### Discover and download 2160p movies
#
  download-movies-2160p-webdl-discover:
    priority: 25
    template:
      - download-movies-discover-base
      - movies-2160p-webdl

  download-movies-2160p-h264-discover:
    priority: 25
    template:
      - download-movies-discover-base
      - movies-2160p-h264

          

##### Discover and download 1080p movies
#
  download-movies-1080p-discover:
    priority: 26
    template:
      - download-movies-discover-base
      - movies-1080p



##### Discover and download 720p movies, if the movie is not recent
#
  download-movies-720p-discover:
    priority: 27
    template:
      - download-movies-discover-base
      - movies-720p



##### Move series from downloads folder to respective folders, along with existing subtitles and adding the files to the subtitle queue
#
  move-series:
    priority: 31
    template:
      - disable-seen-retry
      - series-metainfo
    filesystem:
      path: '/{{secrets.folder.root}}{{secrets.folder.downseries}}'
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    move:
      to: "/{{secrets.folder.root}}{{secrets.folder.series}}{{tvdb_series_name|escape|replace('&#39;', '')|pathscrub}}/"
      filename: "{{tvdb_series_name|escape|replace('&#39;', '')|pathscrub}} - {{tvdb_ep_id|default(series_id)}}{% if tvdb_ep_name|default(False) %} - {{tvdb_ep_name|pathscrub}}{% endif %}{% if quality|default(False) %} - [{{quality}}]{% endif %}"
      along:
        files:
          - srt
          - sub
        subdirs:
          - Subs
      clean_source: 50
    list_add:
      - subtitle_list:
          list: subtitles
          path: "{{location}}"
          remove_after: 7 days
    exec:
      on_exit:
        phase: find '/{{secrets.folder.root}}{{secrets.folder.downseries}}'* -type d -empty -delete


##### Move anime from downloads folder to respective folders
#
  move-anime:
    priority: 32
    template:
      - disable-seen-retry
      - series-guessit
    filesystem:
      path: '/{{secrets.folder.root}}{{secrets.folder.downanime}}'
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    metainfo_series: yes
    accept_all: yes
    move:
      to: "/{{secrets.folder.root}}{{secrets.folder.anime}}{{series_name|default(title)|pathscrub}}/"
      clean_source: 50
    exec:
      allow_background: yes
      on_exit:
        phase:
          - find '/{{secrets.folder.root}}{{secrets.folder.downanime}}'* -type d -empty -delete
### REMOVE THE LINES BELOW IF YOU DONT WANT TO RENAME ANIME WITH THE EXTERNAL SCRIPT
          - '{{secrets.script.animerenamer}}'
      on_output:
        for_accepted: echo "{{location}}" >> '{{secrets.list.animerename}}'


##### Move movies from downloads folder to the movies folder, along with possible subtitles and adding the files to the subtitle queue
#
  move-movies:
    priority: 33
    template:
      - disable-seen-retry
      - movies-metainfo
    filesystem:
      path: '/{{secrets.folder.root}}{{secrets.folder.downmovies}}'
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    regexp:
      reject:
        - \btrailer\b
        - \bsample\b
    move:
      to: '/{{secrets.folder.root}}{{secrets.folder.movies}}'
      filename: "{{tmdb_name|pathscrub}} ({{tmdb_year}}){% if quality|default(False) %} - [{{quality}}]{% endif %}"
      along:
        files:
          - srt
          - sub
        subdirs:
          - Subs
      clean_source: 100
    list_add:
      - subtitle_list:
          list: subtitles
          path: "{{location}}"
          remove_after: 7 days
    exec:
      on_exit:
        phase: find '/{{secrets.folder.root}}{{secrets.folder.downmovies}}'* -type d -empty -delete


##### Download subtitles for the previously queued files
#
  download-subtitles:
    priority: 35
    template:
      - disable-seen-retry
    subtitle_list:
      list: subtitles
    list_match:
      from:
        - subtitle_list:
            list: subtitles
    subliminal:
      exact_match: yes
      languages:
        - eng

##### Clean finished torrents from transmission
#
  clean-transmission:
    priority: 37
    disable: details
    clean_transmission:
      <<: *transmission-settings
      finished_for: 15 day


##### Update trakt series list from local series folders, excluding the ones that already ended
#
  update-series-list:
    priority: 41
    template:
      - disable-seen-retry
      - series-metainfo
    filesystem:
      path: '/{{secrets.folder.root}}{{secrets.folder.series}}'
      retrieve: dirs
    manipulate:
      - title:
          replace:
            regexp: '$'
            format: ' S01E01'
    accept_all: yes
    if:
      - tvdb_status == 'Ended': reject
    list_add:
      - trakt_list:
          account: '{{secrets.trakt.account}}'
          list: '{{secrets.trakt.series}}'
          type: shows


##### Clean the series that already ended from trakt series list
#
  clean-series-list:
    priority: 43
    delay: 8 day
    template:
      - disable-seen-retry
      - series-metainfo
      - pushbullet
    trakt_list:
      account: '{{secrets.trakt.account}}'
      list: '{{secrets.trakt.series}}'
      type: shows
    if:
      - tvdb_status == 'Ended': accept
    list_remove:
      - trakt_list:
          account: '{{secrets.trakt.account}}'
          list: '{{secrets.trakt.series}}'
          type: shows

